---
config:
  flowchart:
  curve: linear
---
graph TD;
	回合开始 --> 玩家操作开始

	玩家操作开始 --> 使用灵石回复灵力
	使用灵石回复灵力 --> 玩家操作开始

	玩家操作开始 --> 用灵力修炼获得修为
	用灵力修炼获得修为 --> 玩家操作结束

	玩家操作开始 --> 挖矿获得灵石
	挖矿获得灵石 --> 玩家操作结束

	玩家操作结束 --> NPC策略更新
	NPC策略更新-->NPC行动
	NPC行动-->回合结算

	回合结算-.->回合开始