---
config:
  flowchart:
  curve: linear
---
graph TD;
	回合开始 --> LLM生成随机事件
	LLM生成随机事件 --> 等待玩家输入
	等待玩家输入 --> LLM生成事件结果


	LLM生成事件结果 --> 等待玩家操作

	等待玩家操作 --> A["调整各工作弟子人数（挖矿，招募）"] -->等待玩家操作
	等待玩家操作 --> B["花灵石扩建宗门（灵库，洞府）"]-->等待玩家操作

	等待玩家操作 -- 玩家结束回合 -->回合结束


	回合结束-.回合结算.->回合开始